# Docs: https://github.com/Azure/webapps-deploy
# More Azure Actions: https://github.com/Azure/actions

name: Build and deploy ASP.NET Core app to Azure Web App - dlt-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" # Automatically uses latest 9 preview

      - name: Restore dependencies
        run: dotnet restore ./DLTAPI/DLTAPI.csproj

      - name: Build project
        run: dotnet build ./DLTAPI/DLTAPI.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish ./DLTAPI/DLTAPI.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dlt-api
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: dlt-api
          path: ./publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1C05F683BA8144A1BDB521B210F0B596 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0841AD13FF3C428098CB08F73AD3E2FA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D11026FA6B41425E90BEB82D707B9CAF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dlt-api"
          slot-name: "Production"
          package: ./publish
